name: CI

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm run install-all

      - name: Set up .env file
        run: echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" > .env

      - name: Run Jest
        run: npm test
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}

  delivery:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ success() }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Fetch branches
        run: git fetch

      - name: Merge develop to main
        run: |
          git checkout main
          git pull origin main
          git merge develop --allow-unrelated-histories --no-ff --no-edit || echo "Merge conflicts detected, please resolve manually"
        
      - name: Push changes
        if: success()
        run: git push origin main || echo "Push failed due to merge conflicts"
        
      - name: Update develop branch
        run: |
          git checkout develop
          git merge main --allow-unrelated-histories --no-ff --no-edit
          git push origin develop || echo "Push to develop failed"
